#!/bin/bash

###############################################################################
# SCRIPT DE SAUVEGARDE PROPREMENT DIT                                         #
# Sauvegarde récursive incrémentale du dossier 'home' de l'utilisateur        #
# courant (~) sur disque externe ou cle USB                                   #
# Ce script est appelé en environnement graphique par le lanceur              #
# et s'exécute dans la fenêtre que ce dernier a ouverte                       #
###############################################################################

###############################################################################
# Configuration de l'interpréteur BASH pour fonctionner en mode 'strict'      #
# afin de faciliter le débogage du script :                                   #
###############################################################################

set -e            # Sortie immédiate si erreur dans commande (code /= de 0)
name=${1:-}       # Redéfinit les arguments d'entrée sous forme de variables
                  # internes au scrip (permet d'utiliser -u avec des
                  # arguments d'entrée - non utilisé ici)
set -u            # Interdit le référencement de variables non définies avant
set -o pipefail   # Empêche le masquage des erreurs dans un pipeline
IFS=$'\n\t'       # IFS correspond à un séparateur de champ interne à Bash
                  # il contrôle ce que Bash appelle le fractionnement de mots

# -----------------------------------------------------------------------------

echo 'Patientez, backup en cours... ';
echo '© Henri';
echo '-----------------------------------------------------------------------------';

sleep 1;

echo "Le backup est en cours d'exécution...";
echo '-----------------------------------------------------------------------------';
echo;

# Le backup est exécuté par la commande 'rsync'
# Le bakslash permet d'écrire les arguments sur plusieurs lignes en supprimant
# l'interprétation du caractère qui le suit immédiatement (saut à la ligne)
# NB : il ne faut pas d'espace après le backslash

rsync -azv --delete   \
--exclude=".cache/"   \
--exclude=".mozilla/" \
--exclude=".local/"   \
--exclude=".config/"  \
--backup --backup-dir=/run/media/disque_et_repertoire_de_stockage_des_fichiers_effaces/ \
~/ \
/run/media/disque_et_repertoire_de_stockage_de_la_sauvegarde/;

sleep 1;
echo;
echo '-----------------------------------------------------------------------------';
echo 'Sauvegarde terminée';
echo '-----------------------------------------------------------------------------';
sleep 1;


# DETAIL DES PARAMETRES DE RSYNC UTILISES POUR LE BACKUP :
# --------------------------------------------------------
# (-n   Simule la sauvegarde sans la faire... NB : à supprimer quand OK !)
#
# -v    Augmente la quantité d'infos imprimées au démarrage
#
# -z    rsync compresses the file data as it is sent to the destination 
#       machine,  which  reduces the amount of data being transmitted
#
# -a    Equivalent to -rlptgoD. It is a quick way of saying you want recursion
#       and want to preserve almost everything
#       (with -H being a notable omission)   =>détails ci-dessous=>
#
# -r    Parcours le dossier indiqué et tous ses sous-dossiers (récursivité)
# -l    Copie les liens symboliques comme liens symboliques
# -p    Permet de garder les fichiers partiellement transférés si interruption
# -t    Préserve les dates
# -g    Préserve le groupe
# -o    Met le propriétaire du fichier de destination identique à celui
#       du fichier source
# -D    Préserve les infos des périphériques
#
# --delete         Efface, dans le backup, les fichiers supprimés mais
# --backup         en garde quand même une copie de sécurité
# --backup-dir=xxx <== ici !
#
# --exclude="XX" Précise les répertoires et fichiers à exclure du backup
#       ATTENTION ! les chemins indiqués ici sont toujours des chemins RELATIFS :
#       ils partent nécessairement du répertoire "source"
